import 'package:modbus_master/modbus_master.dart';

/// - 1000 milliseconds is the timeout. If the slave device does not respond
///   with a response within 1000 milliseconds, then a 'timeout error' response
///   is generated by the Modbus master library.
/// - This program sends 5 read requests to the Modbus/TCP slave device:
///     - Request to read coil no 1
///     - Request to read coil no 2
///     - Request to read coil no 3
///     - Request to read coil no 4
///     - Request to read coil no 5
/// - Each request is sent to the same device, the details of which are as follows:
///     - IPv4 type
///     - IP address 127.0.0.1
///     - Port number 502
///     - Unit ID 1
///     - Timeout 1000 milliseconds
void main() async {
  final modbusMaster = await ModbusMaster.start();

  int countResponseReceived = 0;
  modbusMaster.responseFromSlaveDevices.listen(
    (response) {
      ++countResponseReceived;
      print(response);

      if (countResponseReceived >= 5) {
        modbusMaster.stop();
      }
    },
  );

  for (int i = 1; i <= 5; ++i) {
    try {
      modbusMaster.read(
        ipAddress: '192.168.1.3',
        portNumber: 502,
        unitId: 1,
        blockNumber: 0,
        elementNumber: 2,
        timeoutMilliseconds: 1000,
      );
    } catch (e) {
      // print('EXCEPTION THROWN WHILE READING $e');
    }
    await Future.delayed(Duration(seconds: 2));
  }
}
