name: modbus_master
description: An easy to use package using which a dart program can work as a Modbus/TCP master device.
version: 1.0.0
# publish_to: None
repository: https://github.com/simpleCodeGuy/modbus_master

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
