name: modbus_master
description: An easy to use package using which a dart program can work as a Modbus/TCP master device.
version: 2.0.0
# publish_to: None
repository: https://github.com/simpleCodeGuy/modbus_master

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.0
  simple_logger: ^1.10.0

dev_dependencies:
  # lints: ^4.0.0
  test: ^1.24.0

topics:
- modbus
- tcp
- embedded
- plc
- scada

platforms:
  android:
  ios:
  linux:
  macos:
  windows: